blank_issues_enabled: false
contact_links:
  - name: Pergunta Geral / Suporte
    url: https://github.com/rg-hermann/modules_terraform/discussions
    about: Use Discussions para dúvidas gerais antes de abrir issues.
